### ISSUE TITLE
Some error about "ValueError: math domain error"

### ISSUE THREAD

**Issue by fangdm** [whatshap/whatshap#407] opened 2022-10-25 06:12 UTC
Hello, I am running this command:

`whatshap polyphase -o phased.vcf --reference=ref.fa --mapq 20 --indels --ignore-read-groups --ploidy 3 -t 1 variants.vcf aln.best.sort.bam`

the software runs correctly, but for some contigs, it is raising this error:

```
Traceback (most recent call last):
  File "/hwfssz1/ST_EARTH/Reference/ST_AGRIC/USER/wangfang/02.software/miniconda3/envs/whatshap-env/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/hwfssz1/ST_EARTH/Reference/ST_AGRIC/USER/wangfang/02.software/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/hwfssz1/ST_EARTH/Reference/ST_AGRIC/USER/wangfang/02.software/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/polyphase.py", line 821, in main
    run_polyphase(**vars(args))
  File "/hwfssz1/ST_EARTH/Reference/ST_AGRIC/USER/wangfang/02.software/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/polyphase.py", line 295, in run_polyphase
    ) = phase_single_individual(
  File "/hwfssz1/ST_EARTH/Reference/ST_AGRIC/USER/wangfang/02.software/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/polyphase.py", line 421, in phase_single_individual
    phase_single_block(block_id, block_readset, gt_slices[block_id], param, timers)
  File "/hwfssz1/ST_EARTH/Reference/ST_AGRIC/USER/wangfang/02.software/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/cli/polyphase.py", line 577, in phase_single_block
    paths, haplotypes = run_threading(
  File "/hwfssz1/ST_EARTH/Reference/ST_AGRIC/USER/wangfang/02.software/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/threading.py", line 60, in run_threading
    haplotypes = force_genotypes(
  File "/hwfssz1/ST_EARTH/Reference/ST_AGRIC/USER/wangfang/02.software/miniconda3/envs/whatshap-env/lib/python3.10/site-packages/whatshap/threading.py", line 192, in force_genotypes
    log_likelihood += log(
ValueError: math domain error


```
and the version as:    whatshap --version
1.6

How can i do for it? 

Thank you.

**Comment by schrins** [comment] 2022-10-25 13:03
Looks like the calculation fails for specific allele depths in combination with an intermediate read clustering. Do you have a sharable (and preferably small) instance which produces this error?

**Comment by schrins** [comment] 2022-10-28 12:59
Never mind, I was able to reproduce this behavior on some other instance. I will have a look into it.

**Comment by fangdm** [comment] 2022-10-31 07:22
Thank you very much.
I found that when I added this parameter ‘--distrust-genotypes’, it worked normally, so I suspect that some abnormal mutation sites are causing this error.

**Comment by schrins** [comment] 2022-11-01 14:50
I pushed some changes to a new branch "issue-407". Can you try to re-run your experiment on this version to see if it still crashes?

You would have to clone the git repository manually:
```
git clone https://github.com/whatshap/whatshap.git
git checkout issue-407
```
Depending on whether you used virtual environment or conda (or something else) you need to compile it, which requires some dependencies. There is more information here: https://whatshap.readthedocs.io/en/latest/develop.html
I just see, that the conda command is a bit outdated, because we require Python 3.7 or higher and I think scipy needs to be in there as well. So the install command would rather be `conda create -n whatshap-dev python=3.7 pysam PyVCF pyfaidx xopen Cython pytest sphinx-issues scipy`.

The fact that `--distrust-genotypes` changes the behavior probably has nothing to do with abnormal mutation sites. The flag will cause the phaser to output the genotypes which it thinks are correct when looking at the reads. Otherwise, the phaser will forcefully assume the input genotypes to be 100% correct.

**Comment by schrins** [comment] 2023-03-01 14:13
Closing this, as there seems no remaining issue and the mentioned pull request has been merged.

**Closed by schrins** 2023-03-01 14:13 UTC
