### ISSUE TITLE
conda install not running

### ISSUE THREAD

**Issue by warthmann** [whatshap/whatshap#315] opened 2021-05-28 14:30 UTC
hello, I did several conda installs and I keep getting the error

ImportError: cannot import name 'gcd' from 'fractions' 

Seems a python and whatshap version mismatch, however I am using python 3.9.5 and the most recent version of whatshap (1.1 py39h7cff6ad_0). I got older versions to run, but since I need the subcommand polyploid, they are of no help. Would be great if you could advise. I am on ubuntu 16 and my conda environment looks like the below

$ conda list
 packages in environment at .... miniconda3/envs/whatshap:

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
biopython                 1.78             py39h3811e60_2    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
htslib                    1.12                 h9093b5e_1    bioconda
isa-l                     2.30.0               ha770c72_4    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
networkx                  2.3                        py_0    conda-forge
numpy                     1.20.3           py39hdbf815f_1    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
pigz                      2.6                  h27826a3_0    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pyfaidx                   0.5.9.5            pyh3252c3a_0    bioconda
pysam                     0.16.0.1         py39h051187c_3    bioconda
python                    3.9.5                hdb3f193_3  
python-isal               0.10.0           py39h3811e60_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
scipy                     1.6.3            py39hee8e79c_0    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
whatshap                  1.1              py39h7cff6ad_0    bioconda
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xopen                     1.1.0            py39hf3d152e_2    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge

**Comment by ptrebert** [comment] 2021-05-28 14:43
I cannot confirm this on an Ubuntu 20.04 system - can you please post the exact command line you are running?

**Comment by warthmann** [comment] 2021-05-28 15:12
conda create --name whatshap python=3.9
conda activate whatshap
conda install whatshap=1.1
(whatshap) norman@...$ python --version
Python 3.9.5
(whatshap) norman@...$ whatshap --version
Traceback (most recent call last):
  File "/home/norman/data/miniconda3/envs/whatshap/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/__main__.py", line 60, in main
    module = importlib.import_module("." + module_name, cli_package.__name__)
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/cli/genotype.py", line 31, in <module>
    from whatshap.cli.phase import select_reads, setup_families
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/cli/phase.py", line 40, in <module>
    from whatshap.merge import ReadMerger, DoNothingReadMerger
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/whatshap/merge.py", line 4, in <module>
    from networkx import (
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/networkx/__init__.py", line 114, in <module>
    import networkx.generators
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/networkx/generators/__init__.py", line 14, in <module>
    from networkx.generators.intersection import *
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/networkx/generators/intersection.py", line 13, in <module>
    from networkx.algorithms import bipartite
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/networkx/algorithms/__init__.py", line 16, in <module>
    from networkx.algorithms.dag import *
  File "/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/site-packages/networkx/algorithms/dag.py", line 23, in <module>
    from fractions import gcd
ImportError: cannot import name 'gcd' from 'fractions' (/home/norman/data/miniconda3/envs/whatshap/lib/python3.9/fractions.py)

**Comment by ptrebert** [comment] 2021-05-28 15:46
Ok, I still cannot reproduce this error using the above commands. Checking the `dag` module from the `networkx` package shows that the `gcd` function is imported from `math`, so my two best guesses are that your paths (PATH/PYTHONPATH) are somehow messed up, or that your `conda install` does not update dependencies (e.g., your `.condarc` file contains `update_dependencies: True`)

**Comment by marcelm** [comment] 2021-05-28 20:02
I can reproduce the problem with this `Dockerfile`:
```
FROM ubuntu:xenial
RUN apt-get update && apt-get -y install bzip2 wget
RUN wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/conda
ENV PATH "/opt/conda/bin:$PATH"
RUN conda config --add channels conda-forge --add channels bioconda
RUN conda create -n whatshap whatshap=1.1
ENV PATH /opt/conda/envs/whatshap/bin:$PATH
RUN whatshap --version
```

**Comment by marcelm** [comment] 2021-05-28 20:49
So the problem is definitely that networkx 2.3 gets installed, which isn’t compatible with Python 3.9. It uses `fractions.gcd`, which no longer exists in Python 3.9, and `math.gcd` needs to be used instead, see https://bugs.python.org/issue39350.

One workaround is to explicitly say that you want networkx at version 2.5:
```
conda create -n whatshap whatshap=1.1 networkx=2.5
```
This will actually use Python 3.8 instead. If you want Python 3.9, this also works:
```
conda create -n whatshap whatshap=1.1 networkx=2.5 python=3.9
```
So Python 3.9 and NetworkX 2.5 aren’t actually in conflict but Conda still thinks it’s better to not have them installed at the same time.

We’ll need to depend on `networkx>=2.4` in the Bioconda recipe.

**Comment by ptrebert** [comment] 2021-05-28 21:06
interesting - turns out I couldn't reproduce b/c it's one of the cases where mamba (which I use by default) solves the env apparently "better" than conda and selects networkx 2.5.1

**Comment by marcelm** [comment] 2021-05-29 21:55
The package is now updated, closing this issue now. Please let us know if there’s still a problem.

**Closed by marcelm** 2021-05-29 21:55 UTC
