### ISSUE TITLE
Found 0 reads covering 0 variants

### ISSUE THREAD

**Issue by sinha-shruti** [whatshap/whatshap#307] opened 2021-04-27 12:34 UTC
Hi,
I am trying to run whatshap on pacbio HiFI data "https://www.ncbi.nlm.nih.gov/bioproject/540705". I had done alignment using pbmm2 and the variant calling using GATK.
On running the whatshap, the output vcf file is not phased and for all the chromosomes, I get the following stats.

Using maximum coverage per sample of 15X
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 0
Reading alignments and detecting alleles ...
Found 0 reads covering 0 variants
Kept 0 reads that cover at least two variants each
Reducing coverage to at most 15X by selecting most informative reads ...
Selected 0 reads covering 0 variants
Best-case phasing would result in 0 non-singleton phased blocks (0 in total)
... after read selection: 0 non-singleton phased blocks (0 in total)
Variants covered by at least one phase-informative read in at least one individual after read selection: 0
Phasing 1 sample by solving the MEC problem ...
MEC cost: 0
No. of phased blocks: 0

The command I am running is 
"whatshap phase -o HG001.phased.vcf --ignore-read-groups --reference $reffile unphased.vcf.gz ${maindir}/variant_call/HG001.recalibrated.bam"

I have also tried to run on the original bam file but ended up with the same.
Any help would be appreciated
Thanks

**Comment by markopetek** [comment] 2021-04-30 15:52
I have a similar problem with nanopore alignment of tetraploid potato. I used freebayes to call variants on a small region of interest:

```
freebayes --ploidy 4 --min-alternate-count 2 --use-best-n-alleles 4 \
-f ../../_A_02_Samplix_assembl-dry/input/genome/DM_1-3_516_R44_potato_genome_assembly.v6.1.filtered.scaffoldMerged.fasta \
-b ../input/raw_corr_potatov61.addRG.bam \
--region chr10:57940308-58013972 \
-v ../output/freebayes_raw_corr_potatov61.vcf
```

then I've run:
```
whatshap polyphase -t 30 --ploidy 4 --block-cut-sensitivity 1 \
-o ../output/freebayes_raw_corr_potatov61.phased.vcf \
--reference=../../_A_02_Samplix_assembl-dry/input/genome/DM_1-3_516_R44_potato_genome_assembly.v6.1.filtered.scaffoldMerged.fasta \
--indels \
--include-haploid-sets \
--mapping-quality 1 \
../output/freebayes_raw_corr_potatov61.vcf \
../input/raw_corr_potatov61.addRG.bam
```

This is WhatsHap (polyploid) 1.1 running under Python 3.9.2
======== Working on chromosome 'chr10'
---- Processing individual samplix
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 0
Reading alignments for sample 'samplix' and detecting alleles ...
Found 0 reads covering 0 variants
Kept 0 reads that cover at least two variants each
Detecting connected components with weak interconnect ..
Split heterozygous variants into 0 blocks (and 0 singleton blocks).
======== Writing VCF
Done writing VCF

== SUMMARY ==
Maximum memory usage: 0.257 GB
Time spent reading BAM/CRAM:                    0.9 s
Time spent parsing VCF:                         0.1 s
Time spent detecting blocks:                    0.0 s
Time spent phasing blocks:                      0.1 s
Time spent writing VCF:                         0.1 s
Time spent on rest:                             0.2 s
Total elapsed time:                             1.3 s

**I've further checked the stats:**
```whatshap stats --gtf=../output/freebayes_raw_corr_potatov61.gtf ../output/freebayes_raw_corr_potatov61.vcf```

Found 1 sample(s) in input VCF
Reporting results for sample samplix
Phasing statistics for sample samplix from file ../output/freebayes_raw_corr_potatov61.vcf
---------------- Chromosome chr10 ----------------
     Variants in VCF:     2589
        Heterozygous:        0 (       0 SNVs)
              Phased:        0 (       0 SNVs)
            Unphased:        0 (not considered below)
          Singletons:        0 (not considered below)
              Blocks:        0

Block sizes (no. of variants)
   Median block size:         nan variants
  Average block size:         nan variants
       Largest block:        0    variants
      Smallest block:        0    variants

Block lengths (basepairs)
      Sum of lengths:        0    bp
 Median block length:         nan bp
Average block length:         nan bp
       Longest block:        0    bp
      Shortest block:        0    bp
           Block N50:      nan    bp

**Comment by tobiasmarschall** [comment] 2021-04-30 16:57
Thanks for reporting! Cold one of you maybe share a small example to trigger this problem.
CC @schrins

**Comment by markopetek** [comment] 2021-05-05 07:55
@tobiasmarschall
I'm not allowed to share the data publicly at this point. Can I privately share the input files and commands with you through wetransfer or dropbox (it's 1 Gb in total)?

**Comment by schrins** [comment] 2021-05-05 08:20
Whenever I encountered the problem that no read was detected by the phase command, I had a mismatch of the sample name between VCF and BAM file. If you phase only one sample anyways, the option "--ignrore-read-groups" might be a workaround. However, both of you @markopetek and @sinha-shruti already receive 0 heterozygous variants in the first place, for which of course no overlapping reads will be found. With freebayes I once ran into the issue that it would call the correct variant positions on a tetraploid sample, but report every variant as homozyguous, even though there were reads containing alternative alleles. @markopetek Can you maybe check if your VCF indeed contains no heterozyguous variants? Otherwise you could sent me a VCF file to reproduce the problem myself. It does not have to be the entire VCF, a few kb will probably suffice to reproduce the bug, if it is caused by whatshap.

As for @sinha-shruti 's issue: I did not work with the diploid phasing mode and GATK too much, but maybe you could check as well, if your file does not contain any heterozygosity for whatever reason.

**Comment by tobiasmarschall** [comment] 2021-05-05 08:21
Thanks, @schrins, for looking into this!

**Comment by markopetek** [comment] 2021-05-05 11:54
@schrins, I checked the VCF produced by freebayes and it indeed contains only homozyguous variants (GT field is either 0/0/0/0, 1/1/1/1, 2/2/2/2 or 3/3/3/3). The 'Reference allele observation counts' (RO) look fine, but the 'Alternate allele observation counts' are all 0. So it definitely is a problem of freebayes variant calling - any idea why it behaves that way and how to fix it? I have freebayes v1.3.5 installed, which is the latest version.

**Comment by schrins** [comment] 2021-05-05 12:03
@markopetek Sorry, I have no idea, either. I used it for quite a special purpose, where I already had long aligned contigs from an assembly and wanted to combine it into a VCF. I ended up doing this with paftools, which was possible for this special purpose. I actually used quite an old version of freebayes (0.9.21, not sure why conda installed this one though), so if this is a bug, it must be in there for quite a long time.

**Comment by tobiasmarschall** [comment] 2021-05-05 12:45
Maybe open an issue in the FreeBayes issue tracker then? Can we close this one?

**Comment by schrins** [comment] 2021-05-05 14:16
Let's maybe wait for @sinha-shruti who opened this ticket in the first place. There could still be an issue on our side.

**Comment by sinha-shruti** [comment] 2021-05-06 11:24
Hi,
I re-ran the whole vcf call by GATK, called genotype and performed hard filtering using separate filter-expressions instead of a combined one (seems they don't work properly). I used only the SNPs, Biallelic for the whatshap (ignored the indels).  I was then able to run whatshap properly.  I cannot really pinpoint the exact issue with the vcf file though.

**Comment by tobiasmarschall** [comment] 2021-05-06 13:35
Ok, thanks for the update. I'm closing this now. Please feel free to get in touch in case you encounter any unexpected behavior of WhatsHap.

**Closed by tobiasmarschall** 2021-05-06 13:35 UTC
