### ISSUE TITLE
WhatsHap polyphase Assertion Error

### ISSUE THREAD

**Issue by NaphatCode** [whatshap/whatshap#498] opened 2023-11-16 07:56 UTC
WhatsHap 2.0
Run via Docker quay.io/biocontainers/whatshap:2.0--py38h2494328_0
`whatshap polyphase --ignore-read-groups -o phased.vcf --reference=chr22.fa clair3.vcf.gz sample.bam --ploidy 2`

I ran whatshap polyphase on nanopore data and got this error.

This is WhatsHap (polyploid) 2.0 running under Python 3.8.17
======== Working on chromosome 'chr22'
---- Processing individual SAMPLE
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 229
Found 3138 reads covering 222 variants
Kept 866 reads that cover at least two variants each
Detecting connected components with weak interconnect ..
Split heterozygous variants into 14 blocks (and 0 singleton blocks).
Processing block 1 of 14 with 2 reads and 12 variants.
Processing block 2 of 14 with 4 reads and 25 variants.
Processing block 3 of 14 with 1 reads and 2 variants.
Processing block 4 of 14 with 3 reads and 23 variants.
Processing block 5 of 14 with 2 reads and 13 variants.
Processing block 6 of 14 with 1 reads and 8 variants.
Processing block 7 of 14 with 2 reads and 9 variants.
Processing block 8 of 14 with 1 reads and 32 variants.
Processing block 9 of 14 with 3 reads and 62 variants.
Processing block 10 of 14 with 842 reads and 2 variants.
No minimum in last threaded column!
Stored local cluster id was higher than size of global id vector! 0 31 4
Problem occured at position 0 in row [0, 0]
Traceback (most recent call last):
  File "/usr/local/bin/whatshap", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/usr/local/lib/python3.8/site-packages/whatshap/cli/polyphase.py", line 549, in main
    run_polyphase(**vars(args))
  File "/usr/local/lib/python3.8/site-packages/whatshap/cli/polyphase.py", line 247, in run_polyphase
    ) = phase_single_individual(
  File "/usr/local/lib/python3.8/site-packages/whatshap/cli/polyphase.py", line 315, in phase_single_individual
    result = solve_polyphase_instance(allele_matrix, genotype_list, param, timers, prephasing)
  File "/usr/local/lib/python3.8/site-packages/whatshap/polyphase/algorithm.py", line 80, in solve_polyphase_instance
    phase_single_block(
  File "/usr/local/lib/python3.8/site-packages/whatshap/polyphase/algorithm.py", line 187, in phase_single_block
    threads, haplotypes = run_threading(
  File "/usr/local/lib/python3.8/site-packages/whatshap/polyphase/threading.py", line 51, in run_threading
    assert len(paths) == num_vars
AssertionError 

***I could phase other samples with this command line but with assertion violated message as followed**

Processing block 15 of 19 with 3892 reads and 19 variants.
Assertion violated (Get != Set): 1 0 -nan -nan
Assertion violated (Get != Set): 2 0 -nan -nan
Assertion violated (Get != Set): 2 1 -nan -nan
Assertion violated (Get != Set): 3 0 -nan -nan
.
.
Assertion violated (Get != Set): 3891 3889 -nan -nan
Assertion violated (Get != Set): 3891 3890 -nan -nan
Processing block 16 of 19 with 3 reads and 13 variants.
Processing block 17 of 19 with 1 reads and 7 variants.
Processing block 18 of 19 with 2 reads and 12 variants.
Processing block 19 of 19 with 2 reads and 2 variants.
======== Writing VCF
Done writing VCF
== SUMMARY ==
Maximum memory usage: 1.159 GB
Time spent reading BAM/CRAM:            1.7 s
Time spent parsing VCF:                 0.0 s
Time spent detecting blocks:            0.1 s
Time spent scoring reads:               8.8 s
Time spent solving cluster editing:   692.7 s
Time spent threading haplotypes:        0.9 s
Time spent reordering haplotypes:       0.0 s
Time spent writing VCF:                 0.0 s
Time spent on rest:                     0.1 s
Total elapsed time:                   704.4 s

It would be very appreciated if you could look into this issue. Thank you for your time and guidance in advance.
Best regards,
Niel.

**Comment by schrins** [comment] 2023-11-17 10:07
There seem to be two different issues, because the error messages are not related. I suspect that they are caused by some corner cases, where the algorithm produces invalid values (e.g. NaN), which lead to a crash later on.

One thing I noticed: You called the ´polyphase´ module with a ploidy of 2. Is the regular ´phase´ module suitable for your task? It uses a different algorithm that will not have the same issues.

**Comment by NaphatCode** [comment] 2023-11-17 10:17
Thank you very much for your instantaneous reply and generous support.

Regarding 'phase' module, my intention is to actually compare performance of 'phase' and 'polyphase' modules. 
I also plan to run ´polyphase´ module with a ploidy of <2 on human data with copy number mutations.

**Comment by schrins** [comment] 2023-11-18 15:57
I looked at the code and found possible causes of numeric problems, but I am not too confident that the issues are solved. Especially the "Assertion violated (Get != Set)" messages point to some bigger problem, because there were not single messages, but rather a message for every combination of reads (from 1-0 to 3891-3890). It is quite difficult to trace such errors back because of all the possibilities in a dataset with thousands of reads. I created a new branch names `issue-498` where I push possible fixes and additional debug messages.

There are two ways we could proceed: The first one would be that you clone the whatshap repository, check out the new branch, compile it, rerun the failed tests and report whether something changed (even if it just the error message). I described the procedure in earlier issues, e.g. here:

https://github.com/whatshap/whatshap/issues/480#issuecomment-1711506733

The second option would be to share the data instances that crashed, in case they are not confidential. The sample can be very small (in fact: the smaller the better), as long as the error is reproducable in it. In that case I would track down the error completely myself.

One note regarding ploidies below 2: The `polyphase` module does not support varying ploidies (as in copy number mutations), because the design goal was to phase naturally polyploid species with it. There are essential parts of the algorithm that rely on the assumption that the ploidy is known and fixed. There have been discussions about allowing flexible ploidies, but it would require a lot of rewriting and we never had a concrete application with suitable data to work on such a side project.

**Comment by NaphatCode** [comment] 2023-11-20 06:51
**The output I got with issue-498 version of code is as followed :** 

This is WhatsHap (polyploid) 2.2.dev7+g3ca95e7 running under Python 3.10.13
======== Working on chromosome 'chr22'
---- Processing individual SAMPLE
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 229
Found 3138 reads covering 222 variants
Kept 866 reads that cover at least two variants each
Detecting connected components with weak interconnect ..
Split heterozygous variants into 14 blocks (and 0 singleton blocks).
Processing block 1 of 14 with 2 reads and 12 variants.
Processing block 2 of 14 with 4 reads and 25 variants.
Processing block 3 of 14 with 1 reads and 2 variants.
Processing block 4 of 14 with 3 reads and 23 variants.
Processing block 5 of 14 with 2 reads and 13 variants.
Processing block 6 of 14 with 1 reads and 8 variants.
Processing block 7 of 14 with 2 reads and 9 variants.
Processing block 8 of 14 with 1 reads and 32 variants.
Processing block 9 of 14 with 3 reads and 62 variants.
Processing block 10 of 14 with 842 reads and 2 variants.
**Invalid pred score of inf for tuple [0, 0] at position 1
Invalid pred score of inf for tuple [1, 0] at position 1
Invalid pred score of inf for tuple [2, 0] at position 1
Invalid pred score of inf for tuple [3, 0] at position 1
Invalid pred score of inf for tuple [1, 1] at position 1
Invalid pred score of inf for tuple [2, 1] at position 1
Invalid pred score of inf for tuple [3, 1] at position 1
Invalid pred score of inf for tuple [2, 2] at position 1
Invalid pred score of inf for tuple [3, 2] at position 1
Invalid pred score of inf for tuple [3, 3] at position 1
No minimum among 10 entries in last threaded column!**
Stored local cluster id was higher than size of global id vector! 0 31 4
Empty cluster tuple at position 0 in row [0, 0]
Traceback (most recent call last):
  File "/Users/naphat/miniconda3/miniconda3/envs/whtest/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/Users/naphat/CYP2D6/whatshap/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/Users/naphat/CYP2D6/whatshap/whatshap/cli/polyphase.py", line 552, in main
    run_polyphase(**vars(args))
  File "/Users/naphat/CYP2D6/whatshap/whatshap/cli/polyphase.py", line 253, in run_polyphase
    ) = phase_single_individual(
  File "/Users/naphat/CYP2D6/whatshap/whatshap/cli/polyphase.py", line 318, in phase_single_individual
    result = solve_polyphase_instance(allele_matrix, genotype_list, param, timers, prephasing)
  File "/Users/naphat/CYP2D6/whatshap/whatshap/polyphase/algorithm.py", line 84, in solve_polyphase_instance
    phase_single_block(
  File "/Users/naphat/CYP2D6/whatshap/whatshap/polyphase/algorithm.py", line 190, in phase_single_block
    threads, haplotypes = run_threading(
  File "/Users/naphat/CYP2D6/whatshap/whatshap/polyphase/threading.py", line 51, in run_threading
    assert len(paths) == num_vars
AssertionError

***This fix remove Assertion Violated messages from some sample.** 

For example :
 ======== Working on chromosome 'chr22'
---- Processing individual SAMPLE
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 318
Found 3966 reads covering 290 variants 
Kept 3925 reads that cover at least two variants each
Detecting connected components with weak interconnect ..
Split heterozygous variants into 19 blocks (and 0 singleton blocks).
Processing block 1 of 19 with 6 reads and 39 variants.
Processing block 2 of 19 with 2 reads and 39 variants.
Processing block 3 of 19 with 1 reads and 7 variants.
Processing block 4 of 19 with 3 reads and 8 variants.
Processing block 5 of 19 with 1 reads and 14 variants.
Processing block 6 of 19 with 1 reads and 11 variants.
Processing block 7 of 19 with 2 reads and 20 variants.
Processing block 8 of 19 with 1 reads and 14 variants.
Processing block 9 of 19 with 1 reads and 5 variants.
Processing block 10 of 19 with 1 reads and 33 variants.
Processing block 11 of 19 with 2 reads and 3 variants.
Processing block 12 of 19 with 1 reads and 17 variants.
Processing block 13 of 19 with 1 reads and 22 variants.
Processing block 14 of 19 with 2 reads and 2 variants.
Processing block 15 of 19 with 3892 reads and 19 variants.
Processing block 16 of 19 with 3 reads and 13 variants.
Processing block 17 of 19 with 1 reads and 7 variants.
Processing block 18 of 19 with 2 reads and 12 variants.
Processing block 19 of 19 with 2 reads and 2 variants.
======== Writing VCF
Done writing VCF

== SUMMARY ==
Time spent reading BAM/CRAM:            0.8 s
Time spent parsing VCF:                 0.0 s
Time spent detecting blocks:            0.0 s
Time spent scoring reads:               3.8 s
Time spent solving cluster editing:     0.0 s
Time spent threading haplotypes:        0.3 s
Time spent reordering haplotypes:       0.0 s
Time spent writing VCF:                 0.0 s
Time spent on rest:                     0.1 s
Total elapsed time:                     5.0 s

*** However, this fix also lead to similar crash, in sample that able to write VCF but with Assertion Violated messages.**

This is WhatsHap (polyploid) 2.2.dev7+g3ca95e7 running under Python 3.10.13
======== Working on chromosome 'chr22'
---- Processing individual SAMPLE
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 68
Found 1968 reads covering 67 variants
Kept 1929 reads that cover at least two variants each
Detecting connected components with weak interconnect ..
Split heterozygous variants into 7 blocks (and 0 singleton blocks).
Processing block 1 of 7 with 3 reads and 21 variants.
Processing block 2 of 7 with 2 reads and 3 variants.
Processing block 3 of 7 with 1 reads and 15 variants.
Processing block 4 of 7 with 2 reads and 3 variants.
Processing block 5 of 7 with 1917 reads and 12 variants.
Invalid pred score of inf for tuple [0, 0] at position 2
Invalid pred score of inf for tuple [1, 0] at position 2
Invalid pred score of inf for tuple [2, 0] at position 2
Invalid pred score of inf for tuple [1, 1] at position 2
Invalid pred score of inf for tuple [2, 1] at position 2
Invalid pred score of inf for tuple [2, 2] at position 2
Invalid pred score of inf for tuple [0, 0] at position 3
Invalid pred score of inf for tuple [1, 0] at position 3
Invalid pred score of inf for tuple [2, 0] at position 3
Invalid pred score of inf for tuple [1, 1] at position 3
Invalid pred score of inf for tuple [2, 1] at position 3
Invalid pred score of inf for tuple [2, 2] at position 3
Invalid pred score of inf for tuple [0, 0] at position 4
Invalid pred score of inf for tuple [1, 0] at position 4
Invalid pred score of inf for tuple [2, 0] at position 4
Invalid pred score of inf for tuple [1, 1] at position 4
Invalid pred score of inf for tuple [2, 1] at position 4
Invalid pred score of inf for tuple [2, 2] at position 4
Invalid pred score of inf for tuple [0, 0] at position 5
Invalid pred score of inf for tuple [1, 0] at position 5
Invalid pred score of inf for tuple [2, 0] at position 5
Invalid pred score of inf for tuple [1, 1] at position 5
Invalid pred score of inf for tuple [2, 1] at position 5
Invalid pred score of inf for tuple [2, 2] at position 5
Invalid pred score of inf for tuple [0, 0] at position 6
Invalid pred score of inf for tuple [1, 0] at position 6
Invalid pred score of inf for tuple [2, 0] at position 6
Invalid pred score of inf for tuple [1, 1] at position 6
Invalid pred score of inf for tuple [2, 1] at position 6
Invalid pred score of inf for tuple [2, 2] at position 6
Invalid pred score of inf for tuple [2, 0] at position 7
Invalid pred score of inf for tuple [2, 0] at position 8
Invalid pred score of inf for tuple [2, 0] at position 9
Invalid pred score of inf for tuple [2, 0] at position 10
Invalid pred score of inf for tuple [2, 0] at position 11
No minimum among 1 entries in last threaded column!
Stored local cluster id was higher than size of global id vector! 0 31 2
Empty cluster tuple at position 10 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 9 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 8 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 7 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 6 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 5 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 4 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 3 in row [24576, 24576]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 2 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 1 in row [24576, 24576]
Stored local cluster id was higher than size of global id vector! 0 31 3
Empty cluster tuple at position 0 in row [0, 0]
Traceback (most recent call last):
  File "/Users/naphat/miniconda3/miniconda3/envs/whtest/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/Users/naphat/CYP2D6/whatshap/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/Users/naphat/CYP2D6/whatshap/whatshap/cli/polyphase.py", line 552, in main
    run_polyphase(**vars(args))
  File "/Users/naphat/CYP2D6/whatshap/whatshap/cli/polyphase.py", line 253, in run_polyphase
    ) = phase_single_individual(
  File "/Users/naphat/CYP2D6/whatshap/whatshap/cli/polyphase.py", line 318, in phase_single_individual
    result = solve_polyphase_instance(allele_matrix, genotype_list, param, timers, prephasing)
  File "/Users/naphat/CYP2D6/whatshap/whatshap/polyphase/algorithm.py", line 84, in solve_polyphase_instance
    phase_single_block(
  File "/Users/naphat/CYP2D6/whatshap/whatshap/polyphase/algorithm.py", line 190, in phase_single_block
    threads, haplotypes = run_threading(
  File "/Users/naphat/CYP2D6/whatshap/whatshap/polyphase/threading.py", line 51, in run_threading
    assert len(paths) == num_vars
AssertionError
 
I would consult with my supervisor to find the best data sharing policy without violating regulations. In the meantime, I hope these output provide insights toward solution of this issue. I would like to thank you again for your time, elaborate & instantaneous supports which mean the world to me. 
Best regards,
Niel.

**Comment by schrins** [comment] 2023-11-20 15:15
Thanks, your input was quite helpful. I think I found the issue: The high coverage on some blocks (>=800X) caused numeric artifacts, where some likelihoods became so small, that their 64bit-representation became zero. There are now some countermeasures and fallbacks to prevent this. Your VCF and BAM file are now running without any errors.

**Comment by NaphatCode** [comment] 2023-11-22 09:04
Sorry for late reply. I had taken couple days to test 'polyphase' module from WhatsHap version 2.2.dev9+g18b518d with other test data. 
It appears that your fix resolves many issues effectively.
1.  'polyphase' module can be ran successfully across all test samples now. (Some large sample with >8000 reads used to cause WhatsHap polyphase 2.0 to freeze and hence the run is automatically killed. I intended to fix this by running on server, but it's runnable on MacBook now)
2. Phased VCFs can be used for downstream analysis across all test samples as well ( Previously, phased VCF of some test sample can't be genotyped by PyPGx. )

Thank you very much for your extensive guidance throughout the issue. It would be impossible to progress without your support. Your attention to the issue is very much appreciated on the user end. The unwavering support is highly appreciated, both professionally and personally.

Niel.

**Comment by schrins** [comment] 2023-11-22 09:44
Good to hear, that the fix was helpful for your project. I will close this issue and create a pull request for the fixed code. If there are more errors, feel free to re-open or create a new issue.

**Closed by schrins** 2023-11-22 09:44 UTC

**Comment by senthilk88** [comment] 2023-12-21 20:10
Hello I face similar error in my data, which is a tetraploid potato species. is there anyway I could access the above said version 2.2 of whatshap ?. I'm inserting the error messages here

processing block 4773 of 8714 with 19 reads and 21 variants.
Processing block 4774 of 8714 with 20 reads and 11 variants.
Processing block 4775 of 8714 with 461 reads and 4468 variants.
Processing block 4776 of 8714 with 251 reads and 1945 variants.
Processing block 4777 of 8714 with 260 reads and 2136 variants.
Processing block 4778 of 8714 with 147 reads and 1337 variants.
Processing block 4779 of 8714 with 759 reads and 3941 variants.
Processing block 4780 of 8714 with 2482 reads and 11847 variants.
Traceback (most recent call last):
  File "/home/roots/shanmuse/miniconda3/bin/whatshap", line 8, in <module>
    sys.exit(main())
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/cli/polyphase.py", line 549, in main
    run_polyphase(**vars(args))
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/cli/polyphase.py", line 247, in run_polyphase
    ) = phase_single_individual(
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/cli/polyphase.py", line 315, in phase_single_individual
    result = solve_polyphase_instance(allele_matrix, genotype_list, param, timers, prephasing)
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/polyphase/algorithm.py", line 80, in solve_polyphase_instance
    phase_single_block(
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/polyphase/algorithm.py", line 214, in phase_single_block
    res = solve_polyphase_instance(subm, subgeno, sub_param, timers, quiet=True)
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/polyphase/algorithm.py", line 80, in solve_polyphase_instance
    phase_single_block(
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/polyphase/algorithm.py", line 214, in phase_single_block
    res = solve_polyphase_instance(subm, subgeno, sub_param, timers, quiet=True)
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/polyphase/algorithm.py", line 80, in solve_polyphase_instance
    phase_single_block(
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/polyphase/algorithm.py", line 187, in phase_single_block
    threads, haplotypes = run_threading(
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/polyphase/threading.py", line 42, in run_threading
    affine_switch_cost = ceil(compute_readlength_snp_distance_ratio(allele_matrix) / 1.0)
  File "/home/roots/shanmuse/miniconda3/lib/python3.9/site-packages/whatshap/polyphase/threading.py", line 69, in compute_readlength_snp_distance_ratio
    return length / len(allele_matrix)
ZeroDivisionError: division by zero

please let me know

**Comment by DavCP** [comment] 2024-01-11 17:51
I´m having a similar issue with my data when using the polyphase option. Phasing works as expected when using the phase option but when trying with plyphase I´m getting the following output.

======== Working on chromosome 'T511-LG14_Aco014822_L411'
---- Processing individual T511_supercontig.fasta
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 8
Found 5077 reads covering 8 variants
Kept 1254 reads that cover at least two variants each
Detecting connected components with weak interconnect ..
Split heterozygous variants into 2 blocks (and 0 singleton blocks).
Processing block 1 of 2 with 81 reads and 5 variants.
Processing block 2 of 2 with 1173 reads and 3 variants.
Assertion violated (Get != Set): 2 1 -nan -nan
Assertion violated (Get != Set): 3 1 -nan -nan
Assertion violated (Get != Set): 3 2 -nan -nan
Assertion violated (Get != Set): 4 1 -nan -nan
No minimum in last threaded column!
Stored local cluster id was higher than size of global id vector! 0 31 2
Problem occured at position 4 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 2
Problem occured at position 3 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 2
Problem occured at position 2 in row [4294967295, 4294967295]
Stored local cluster id was higher than size of global id vector! 0 31 4
Problem occured at position 1 in row [0, 0]
Stored local cluster id was higher than size of global id vector! 0 31 2
Problem occured at position 0 in row [0, 0]
Traceback (most recent call last):
  File "/home/plancarte/.local/bin/whatshap", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/plancarte/.local/lib/python3.12/site-packages/whatshap/__main__.py", line 64, in main
    module.main(args)
  File "/home/plancarte/.local/lib/python3.12/site-packages/whatshap/cli/polyphase.py", line 552, in main
    run_polyphase(**vars(args))
  File "/home/plancarte/.local/lib/python3.12/site-packages/whatshap/cli/polyphase.py", line 253, in run_polyphase
    ) = phase_single_individual(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plancarte/.local/lib/python3.12/site-packages/whatshap/cli/polyphase.py", line 318, in phase_single_individual
    result = solve_polyphase_instance(allele_matrix, genotype_list, param, timers, prephasing)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/plancarte/.local/lib/python3.12/site-packages/whatshap/polyphase/algorithm.py", line 84, in solve_polyphase_instance
    phase_single_block(
  File "/home/plancarte/.local/lib/python3.12/site-packages/whatshap/polyphase/algorithm.py", line 190, in phase_single_block
    threads, haplotypes = run_threading(
                          ^^^^^^^^^^^^^^
  File "/home/plancarte/.local/lib/python3.12/site-packages/whatshap/polyphase/threading.py", line 51, in run_threading
    assert len(paths) == num_vars
AssertionError


In some loci I get the following:

======== Working on chromosome 'T511-LG07_Aco014501_L335'
---- Processing individual T511_supercontig.fasta
Number of variants skipped due to missing genotypes: 0
Number of remaining heterozygous variants: 8
Found 1067 reads covering 8 variants
Kept 148 reads that cover at least two variants each
Detecting connected components with weak interconnect ..
Split heterozygous variants into 2 blocks (and 0 singleton blocks).
Processing block 1 of 2 with 59 reads and 3 variants.
Processing block 2 of 2 with 89 reads and 4 variants.
======== Writing VCF
Done writing VCF

But in most of them I get the Assertion violated one.

Btw, as suggested by schrins I installed the unreleased development version 2.2.dev10+g2a2077c.

I'll be really grateful if you guys can help me figure this out
